### ISSUE TITLE
[BUG] 로그인 시 이메일과 패스워드의 validation이 잘 작동하지 않는 경우가 있는 것 같습니다.

### ISSUE THREAD

**Issue by yjeong-k** [wafflestudio19-5/team10-server#55]
안녕하세요!
로그인을 할 때 이메일과 패스워드의 체크가 잘 작동하지 않는 경우가 있는 것 같습니다.
TEST@naver.com와 password 8글자로 가입을 하였는데
1) TEST@naver.com을 입력하고 password를 아무거나 입력하였을 때,
2) test@naver.com으로 로그인을 시도할 때,
모두 같은 계정으로 로그인이 됩니다. 아래 영상을 첨부합니다.

중간총회까지 너무 고생많으셨습니다☺️
스프린트1 발표 때부터 너무 잘 구현해주셔서 매번 감탄하면서 봤습니다.
이번에도 실제 사운드 클라우드와 엄청 비슷하게 잘 구현해주셔서 정말 잘 보았습니다.👍

1)
https://user-images.githubusercontent.com/65206075/148636132-644095e3-96bc-4d32-b734-158e97d9fd20.mov

2)
https://user-images.githubusercontent.com/65206075/148636240-d59233e9-7851-4761-8172-82727c8d6222.mov

**Comment by askrid** [comment]
@yjeong-k 버그 제보 감사합니다!

패스워드 검사 없이 그냥 로그인이 성공되는 현상은 수정하겠습니다.

이메일의 경우, 장고의 기본 인증 백엔드인 `django.contrib.auth.backends.ModelBackend`에서 대소문자를 구분하지 않기 때문에 기존의 이메일로 로그인이 되는 것 같습니다. 일반적으로도 이메일은 대소문자를 구분하지 않는 것으로 알고 있습니다.
